### ISSUE TITLE
HWIMOBUILDscript  is not found

### ISSUE THREAD

**Issue by El-H-git** [cloudfoundry-incubator/bosh-rackhd-cpi-release#2]
Hi,
I have a problem with running ./HWIMO­BUILD.
HWIMOBUILD script is not in the path. So I could not find and run it.
Please help me with that. 

Thanks in advance,
Elham

**Comment by tn5993** [comment]
The HWIMOBUILD scripts are in components of RackHD (on-http, on-taskgraph) at https://github.com/RackHD/RackHD. I assumed that you refer to this docs for integrating RackHD and CloudFoundry using Bosh-RackHD-CPI. https://github.com/cloudfoundry-incubator/bosh-rackhd-cpi-release/blob/master/docs/how_to_deploy_cloud_foundry_on_bare-metal_machine(s).md. Please let me know if you have anymore question

**Comment by El-H-git** [comment]
Thanks
